### ISSUE TITLE
Possible to uninstall packs?

### ISSUE THREAD

**Issue by 7wells** [Tavisco/RVGL-Assistant_Android#7]
Hello!
Is it possible to uninstall packs?

**Comment by Tavisco** [comment]
Hi! Sorry to inform this, but this project is no longer maintained. Feel free to fork it if desired.

**Comment by 7wells** [comment]
Hi Tavisco,

I am sad to hear about this, as it is really a great and helpful tool. May I ask you if you found something else for its purpose? Anyway, I thank you very much for having created this and wish you all the best! 👍

**Comment by Tavisco** [comment]
Hi @7wells! I've updated the `readme.md` file on the root of the project with more details, I really enjoyed developing it at the time, but right now it does not make more sense to work with the current codebase, as I mentioned a complete rewrite would be desirable. Unfortunately I do not know any other alternative to this app, and thanks for the wishes! Wish the best to you too!
